### ISSUE TITLE
工程编译错误

### ISSUE THREAD

**Issue by TCSYANG** [HaiMianBBao/CherryUSB-CH58x-DAPLink#1]
../dap_main.c中的usbd_cdc_acm_init_intf(&intf0)和usbd_cdc_acm_init_intf(&intf1)编译时报错，没有找到usbd_cdc_acm_init_intf()这个函数的定义

**Comment by HaiMianBBao** [comment]
工程下面的子模块克隆下来了吗？

**Comment by TCSYANG** [comment]
执行子模块克隆的命令出现错误，没有找到仓库，我就从仓库里面手动下载，粘贴到工程对应的目录里，就这一个函数找不到，

**Comment by HaiMianBBao** [comment]
你自己手动下载的cherryusb版本跟仓库里面的子模块版本是对不上的，你给你的git配置一下ssh，然后再执行子模块更新命令。
