### ISSUE TITLE
克隆错误

### ISSUE THREAD

**Issue by TCSYANG** [HaiMianBBao/CherryUSB-CH58x-DAPLink#2]
PS E:\wch\CherryUSB-CH58x-DAPLink> git submodule update --init --recursive
Submodule 'CherryUSB-Daplink' (git@github.com:HaiMianBBao/CherryUSB-Daplink.git) registered for path 'CherryUSB-Daplink'
Cloning into 'E:/wch/CherryUSB-CH58x-DAPLink/CherryUSB-Daplink'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HaiMianBBao/CherryUSB-Daplink.git' into submodule path 'E:/wch/CherryUSB-CH58x-DAPLink/CherryUSB-Daplink' failed
Failed to clone 'CherryUSB-Daplink'. Retry scheduled
Cloning into 'E:/wch/CherryUSB-CH58x-DAPLink/CherryUSB-Daplink'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HaiMianBBao/CherryUSB-Daplink.git' into submodule path 'E:/wch/CherryUSB-CH58x-DAPLink/CherryUSB-Daplink' failed
Failed to clone 'CherryUSB-Daplink' a second time, aborting
PS E:\wch\CherryUSB-CH58x-DAPLink>

**Comment by HaiMianBBao** [comment]
给你的git配置ssh

**Comment by TCSYANG** [comment]
哦哦，之前已经配置过了，但不知道为啥这个工程还要手动验证一次
